export const fakeProductCards = [
  {
    "id": 1,
    "title": "Nabeul Ceramic Plate",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 38,
    "story": "Hand-painted with ancestral geometric patterns using cobalt minerals from the Cap Bon peninsula",
    "category": "Pottery",
    "materials": ["Faience clay", "Tin glaze"],
    "tags": ["Heritage pattern", "Wall decor"],
    "rating": 4.9,
    "reviews": 47,
    "stock": 12,
    "image": "/fake/products/product (7).png"

  },
  {
    "id": 2,
    "title": "Nabeul Flower Vase",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 65,
    "story": "Slender vessel featuring Ottoman-inspired tulip motifs, fired in traditional wood kilns",
    "category": "Pottery",
    "materials": ["Terracotta", "Mineral pigments"],
    "tags": ["Table centerpiece", "Wedding gift"],
    "rating": 4.7,
    "reviews": 32,
    "stock": 8,
    "image": "/fake/products/product (27).png"

  },
  {
    "id": 3,
    "title": "Nabeul Tagine Pot",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 52,
    "story": "Conical-lidded cooker designed for slow simmering of lamb with prunes and almonds",
    "category": "Pottery",
    "materials": ["Glazed earthenware"],
    "tags": ["Cooking utensil", "Oven-safe"],
    "rating": 4.8,
    "reviews": 41,
    "stock": 15,
    "image": "/fake/products/product (24).png"
  },
  {
    "id": 4,
    "title": "Perfume Burner (Mabkhara)",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 45,
    "story": "Perforated dome releasing jasmine-infused smoke during traditional ceremonies",
    "category": "Pottery",
    "materials": ["Ceramic", "Wood lid"],
    "tags": ["Aromatherapy", "Wedding ritual"],
    "rating": 4.6,
    "reviews": 28,
    "stock": 7,
    "image": "/fake/products/product (65).png"
  },
  {
    "id": 5,
    "title": "Zellige Tile Panel",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 120,
    "story": "9-piece mosaic recreating Andalusian palace patterns with lapis lazuli accents",
    "category": "Pottery",
    "materials": ["Hand-cut tiles", "Cement base"],
    "tags": ["Wall art", "Architectural element"],
    "rating": 5.0,
    "reviews": 19,
    "stock": 3,
    "image": "/fake/products/product (4).png"
  },
  {
    "id": 6,
    "title": "Fruit Serving Bowl",
    "artisan": "Nabeul Potter",
    "region": "Nabeul",
    "price": 48,
    "story": "Sun-shaped bowl with raised edges for displaying seasonal fruits at festivities",
    "category": "Pottery",
    "materials": ["Painted faience"],
    "tags": ["Tableware", "Holiday serving"],
    "rating": 4.5,
    "reviews": 36,
    "stock": 10,
    "image": "/fake/products/product (72).png"
  },
  {
    "id": 7,
    "title": "Guellala Water Jar",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 85,
    "story": "Porous amphora cooling water through evaporation in Berber courtyards",
    "category": "Ceramics",
    "materials": ["Unglazed terracotta"],
    "tags": ["Desert technology", "Sustainable"],
    "rating": 4.7,
    "reviews": 53,
    "stock": 6,
    "image": "/fake/products/product (50).png"
  },
  {
    "id": 8,
    "title": "Guellala Cooking Tajine",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 42,
    "story": "Earthenware vessel for communal stews, seasoned through generations of use",
    "category": "Ceramics",
    "materials": ["Red clay"],
    "tags": ["Family meals", "Flavor enhancer"],
    "rating": 4.9,
    "reviews": 67,
    "stock": 18,
    "image": "/fake/products/product (53).png"
  },
  {
    "id": 9,
    "title": "Incense Burner (Majmar)",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 28,
    "story": "Miniature pyramid with triangular vents for desert resin purification rituals",
    "category": "Ceramics",
    "materials": ["Terracotta"],
    "tags": ["Spiritual", "Meditation aid"],
    "rating": 4.3,
    "reviews": 22,
    "stock": 14,
    "image": "/fake/products/product (43).png"
  },
  {
    "id": 10,
    "title": "Oil Lamp (Qandil)",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 31,
    "story": "Ancient-design lamp with finger-grooved handle for nocturnal fishing trips",
    "category": "Ceramics",
    "materials": ["Local clay"],
    "tags": ["Historical replica", "Emergency light"],
    "rating": 4.6,
    "reviews": 39,
    "stock": 9,
    "image": "/fake/products/product (64).png"
  },
  {
    "id": 11,
    "title": "Camel Figurine",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 23,
    "story": "Symbol of Saharan travel, molded from clay gathered near Ghriba synagogue",
    "category": "Ceramics",
    "materials": ["Djerba clay"],
    "tags": ["Souvenir", "Desert spirit"],
    "rating": 4.8,
    "reviews": 44,
    "stock": 20,
    "image": "/fake/products/product (33).png"
  },
  {
    "id": 12,
    "title": "Grain Storage Jar",
    "artisan": "Guellala Ceramist",
    "region": "Djerba",
    "price": 78,
    "story": "Wide-bellied vessel preserving harvests through drought seasons",
    "category": "Ceramics",
    "materials": ["Terracotta", "Palm-fiber lid"],
    "tags": ["Food preservation", "Pantry essential"],
    "rating": 4.9,
    "reviews": 38,
    "stock": 11,
    "image": "/fake/products/product (70).png"
  },
  {
    "id": 13,
    "title": "Kairouan Medallion Carpet",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 850,
    "story": "Centerpiece carpet with 400 knots/sq inch, woven for Ramadan gatherings",
    "category": "Textiles",
    "materials": ["Handspun wool"],
    "tags": ["Heirloom", "UNESCO heritage"],
    "rating": 5.0,
    "reviews": 29,
    "stock": 2,
    "image": "/fake/products/product (74).png"
  },
  {
    "id": 14,
    "title": "Prayer Rug (Sajjada)",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 220,
    "story": "Mihrab-arch design oriented toward Mecca with silk-thread highlights",
    "category": "Textiles",
    "materials": ["Wool", "Silk accents"],
    "tags": ["Religious", "Travel companion"],
    "rating": 4.9,
    "reviews": 57,
    "stock": 7,
    "image": "/fake/products/product (34).png"
  },
  {
    "id": 15,
    "title": "Bridal Carpet (Zarbia)",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 1200,
    "story": "Dowry piece requiring 8 months' labor, featuring fertility symbols",
    "category": "Textiles",
    "materials": ["Merino wool"],
    "tags": ["Wedding gift", "Investment piece"],
    "rating": 5.0,
    "reviews": 18,
    "stock": 1,
    "image": "/fake/products/product (38).png"
  },
  {
    "id": 16,
    "title": "Room-Size Carpet",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 1950,
    "story": "Grand reception carpet with border patterns from Great Mosque architecture",
    "category": "Textiles",
    "materials": ["Wool", "Cotton base"],
    "tags": ["Palatial", "Status symbol"],
    "rating": 4.8,
    "reviews": 15,
    "stock": 1,
    "image": "/fake/products/product (37).png"
  },
  {
    "id": 17,
    "title": "Accent Rug (Khoti)",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 165,
    "story": "Doorway guardian with diamond lattice to trap negative energy",
    "category": "Textiles",
    "materials": ["Wool"],
    "tags": ["Protective", "Entryway decor"],
    "rating": 4.7,
    "reviews": 42,
    "stock": 9,
    "image": "/fake/products/product (41).png"
  },
  {
    "id": 18,
    "title": "Cushion Cover (Mekass)",
    "artisan": "Kairouan Rug Weaver",
    "region": "Kairouan",
    "price": 95,
    "story": "Miniature carpet technique adapted for seating, with silk tassels",
    "category": "Textiles",
    "materials": ["Wool", "Silk threads"],
    "tags": ["Home accent", "Modular design"],
    "rating": 4.6,
    "reviews": 63,
    "stock": 14,
    "image": "/fake/products/product (45).png"
  },
  {
    "id": 19,
    "title": "Berber Blanket (Fouta)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 115,
    "story": "Nomadic warmth woven with undyed wool from mountain-grazed sheep",
    "category": "Textiles",
    "materials": ["Sheep wool"],
    "tags": ["Nomadic life", "Hypoallergenic"],
    "rating": 4.8,
    "reviews": 88,
    "stock": 22,
    "image": "/fake/products/product (58).png"
  },
  {
    "id": 20,
    "title": "Tent Panel (Klim)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 240,
    "story": "Portable home section with tribal marriage symbols in crimson and indigo",
    "category": "Textiles",
    "materials": ["Goat hair", "Wool"],
    "tags": ["Cultural preservation", "Movable wall"],
    "rating": 4.9,
    "reviews": 37,
    "stock": 5,
    "image": "/fake/products/product (52).png"
  },
  {
    "id": 21,
    "title": "Cushion Cover (M'tass)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 45,
    "story": "Geometric storytelling through triangles representing mountain peaks",
    "category": "Textiles",
    "materials": ["Wool", "Leather piping"],
    "tags": ["Symbolic art", "Sofa transformation"],
    "rating": 4.7,
    "reviews": 121,
    "stock": 30,
    "image": "/fake/products/product (57).png"
  },
  {
    "id": 22,
    "title": "Storage Bag (Koffa)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 68,
    "story": "Bride's trousseau carrier with reinforced handles for desert journeys",
    "category": "Textiles",
    "materials": ["Wool", "Goat hair straps"],
    "tags": ["Wedding essential", "Durable"],
    "rating": 4.5,
    "reviews": 56,
    "stock": 17,
    "image": "/fake/products/product (75).png"
  },
  {
    "id": 23,
    "title": "Shawl (Burnous)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 89,
    "story": "Hooded shepherd's cloak with hidden pockets for medicinal herbs",
    "category": "Textiles",
    "materials": ["Lanolin-rich wool"],
    "tags": ["Weatherproof", "Unisex"],
    "rating": 4.6,
    "reviews": 72,
    "stock": 13,
    "image": "/fake/products/product (61).png"
  },
  {
    "id": 24,
    "title": "Bridal Belt (Hzam)",
    "artisan": "Berber Weaver",
    "region": "Kesra",
    "price": 155,
    "story": "Seven-strand fertility belt with silver amulet casings",
    "category": "Textiles",
    "materials": ["Silk", "Silver coins"],
    "tags": ["Ceremonial", "Ancestral craft"],
    "rating": 4.9,
    "reviews": 41,
    "stock": 4,
    "image": "/fake/products/product (59).png"
  },
  {
    "id": 25,
    "title": "Engraved Tray (Siniya)",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 185,
    "story": "Moon-shaped serving tray with Quranic verse borders",
    "category": "Metalwork",
    "materials": ["Hammered copper"],
    "tags": ["Ceremonial serving", "Patina finish"],
    "rating": 4.9,
    "reviews": 64,
    "stock": 9,
    "image": "/fake/products/product (42).png"
  },
  {
    "id": 26,
    "title": "Chemsiya Lantern",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 110,
    "story": "Starburst-patterned light caster for Ramadan nights",
    "category": "Metalwork",
    "materials": ["Copper", "Glass panels"],
    "tags": ["Atmospheric lighting", "Mosque-inspired"],
    "rating": 4.8,
    "reviews": 93,
    "stock": 15,
    "image": "/fake/products/product (11).png"
  },
  {
    "id": 27,
    "title": "Coffee Pot (Rouwaya)",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 95,
    "story": "Long-spouted server for ceremonial pouring height",
    "category": "Metalwork",
    "materials": ["Copper", "Brass handle"],
    "tags": ["Hospitality symbol", "Pine-cone finial"],
    "rating": 4.7,
    "reviews": 78,
    "stock": 11,
    "image": "/fake/products/product (32).png"
  },
  {
    "id": 28,
    "title": "Ewer & Basin Set",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 230,
    "story": "Welcome ritual set with rosewater containment",
    "category": "Metalwork",
    "materials": ["Copper", "Brass inlay"],
    "tags": ["Guest honor", "Wedding set"],
    "rating": 5.0,
    "reviews": 49,
    "stock": 6,
    "image": "/fake/products/product (49).png"
  },
  {
    "id": 29,
    "title": "Finjan Holder",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 75,
    "story": "Ornate stand preventing heat transfer to surfaces",
    "category": "Metalwork",
    "materials": ["Repoussé copper"],
    "tags": ["Coffee ritual", "Table protector"],
    "rating": 4.6,
    "reviews": 85,
    "stock": 18,
    "image": "/fake/products/product (46).png"
  },
  {
    "id": 30,
    "title": "Decorative Plate",
    "artisan": "Coppersmith",
    "region": "Tunis",
    "price": 150,
    "story": "Wall art with chasing technique depicting Medina archways",
    "category": "Metalwork",
    "materials": ["Oxidized copper"],
    "tags": ["Architectural tribute", "Patina art"],
    "rating": 4.9,
    "reviews": 36,
    "stock": 7,
    "image": "/fake/products/product (54).png"
  },
  {
    "id": 31,
    "title": "Harvest Basket",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 55,
    "story": "Double-walled carrier for date harvesting with shoulder strap",
    "category": "Basketwork",
    "materials": ["Dried palm fronds"],
    "tags": ["Agricultural tool", "Ergonomic"],
    "rating": 4.7,
    "reviews": 112,
    "stock": 25,
    "image": "/fake/products/product (63).png"
  },
  {
    "id": 32,
    "title": "Kabbous Hat",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 28,
    "story": "Conical sun protector with internal sweatband",
    "category": "Basketwork",
    "materials": ["Palm leaves", "Cotton lining"],
    "tags": ["Farmers' gear", "UV protection"],
    "rating": 4.4,
    "reviews": 167,
    "stock": 42,
    "image": "/fake/products/product (44).png"
  },
  {
    "id": 33,
    "title": "Decorative Mat (Hasira)",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 75,
    "story": "Prayer surface with directional weave pattern",
    "category": "Basketwork",
    "materials": ["Dyed palm fibers"],
    "tags": ["Meditation aid", "Wall tapestry"],
    "rating": 4.6,
    "reviews": 58,
    "stock": 16,
    "image": "/fake/products/product (56).png"
  },
  {
    "id": 34,
    "title": "Hand Fan (Mirkha)",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 19,
    "story": "Wedding guest favor with henna pattern inspiration",
    "category": "Basketwork",
    "materials": ["Palm leaf", "Bamboo handle"],
    "tags": ["Summer essential", "Bridal party"],
    "rating": 4.3,
    "reviews": 204,
    "stock": 65,
    "image": "/fake/products/product (62).png"
  },
  {
    "id": 35,
    "title": "Fruit Serving Tray",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 42,
    "story": "Coiled design allowing airflow to preserve freshness",
    "category": "Basketwork",
    "materials": ["Palm stems", "Reinforced rim"],
    "tags": ["Table organizer", "Natural venting"],
    "rating": 4.8,
    "reviews": 91,
    "stock": 28,
    "image": "/fake/products/product (73).png"
  },
  {
    "id": 36,
    "title": "Woven Camel Figurine",
    "artisan": "Palm Leaf Weaver",
    "region": "Tozeur",
    "price": 32,
    "story": "Caravan tribute with date-palm hump symbolism",
    "category": "Basketwork",
    "materials": ["Palm leaflets", "Acacia thorns"],
    "tags": ["Desert souvenir", "Symbol of endurance"],
    "rating": 4.9,
    "reviews": 77,
    "stock": 37,
    "image": "/fake/products/product (68).png"
  }
]
