export const fakeArtisanCards = [
  {
    "id": 1,
    "name": "Hakim Ben Nasr",
    "location": "Nabeul",
    "region": "nabeul",
    "craft": "potter",
    "materials": ["clay", "tin-glaze", "cobalt-pigment"],
    "culturalTags": ["family-workshop", "coastal-craft"],
    "quote": "The blue of our pottery reflects both the Mediterranean sky and centuries of Andalusian heritage.",
    "rating": 4.8,
    "totalOrders": 287,
    "yearsActive": 15,
    "specialty": "Hand-painted Faience",
    "heritage": "Nabeul ceramic tradition",
    "accepts": "custom-orders",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (10).png",
    "workshop": "/fake/workshops/workshop (5).png",
    "products": ["/fake/products/product (50).png", "/fake/products/product (43).png"]
  },
  {
    "id": 2,
    "name": "Leila Dridi",
    "location": "Guellala",
    "region": "djerba",
    "craft": "ceramist",
    "materials": ["terracotta-clay", "natural-ochre"],
    "culturalTags": ["functional-art", "island-heritage"],
    "quote": "Our clay remembers the hands of Phoenician ancestors - each pot carries their practical wisdom.",
    "rating": 4.6,
    "totalOrders": 154,
    "yearsActive": 12,
    "specialty": "Unglazed Water Jars",
    "heritage": "Djerba island pottery",
    "accepts": "bulk-orders",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (19).png",
    "workshop": "/fake/workshops/workshop (3).png",
    "products": ["/fake/products/product (24).png", "/fake/products/product (65).png", "/fake/products/product (36).png"]
  },
  {
    "id": 3,
    "name": "Fatima Kacem",
    "location": "Kairouan",
    "region": "kairouan",
    "craft": "rug-weaver",
    "materials": ["handspun-wool", "madder-root-dye"],
    "culturalTags": ["women-led", "sacred-city"],
    "quote": "When my fingers tie knots, I weave prayers from the Great Mosque into something tangible.",
    "rating": 5.0,
    "totalOrders": 422,
    "yearsActive": 27,
    "specialty": "Kairouan Medallion Carpets",
    "heritage": "UNESCO Intangible Heritage",
    "accepts": "custom-designs",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (5).png",
    "workshop": "/fake/workshops/workshop (6).png",
    "products": ["/fake/products/product (74).png", "/fake/products/product (45).png"]
  },
  {
    "id": 4,
    "name": "Idir Amazigh",
    "location": "Kesra",
    "region": "siliana",
    "craft": "textile-weaver",
    "materials": ["mountain-wool", "walnut-dye"],
    "culturalTags": ["berber-symbols", "mountain-craft"],
    "quote": "These geometric patterns are maps - they chart our history across Atlas Mountains and Sahara.",
    "rating": 4.7,
    "totalOrders": 198,
    "yearsActive": 19,
    "specialty": "Tribal Pattern Blankets",
    "heritage": "Amazigh ancestral weaving",
    "accepts": "commissions",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (20).png",
    "workshop": "/fake/workshops/workshop (4).png",
    "products": ["/fake/products/product (61).png", "/fake/products/product (58).png"]
  },
  {
    "id": 5,
    "name": "Youssef Hammoud",
    "location": "Sfax",
    "region": "sfax",
    "craft": "coppersmith",
    "materials": ["hammered-copper", "brass-inlay"],
    "culturalTags": ["medina-artisan", "sound-craft"],
    "quote": "The rhythm of my hammer is the heartbeat of the souk - transforming metal into moonlight.",
    "rating": 4.9,
    "totalOrders": 331,
    "yearsActive": 23,
    "specialty": "Filigree Lamps",
    "heritage": "Ancient metalworking",
    "accepts": "custom-engraving",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (27).png",
    "workshop": "/fake/workshops/workshop (1).png",
    "products": ["/fake/products/product (42).png", "/fake/products/product (54).png", "/fake/products/product (49).png"]
  },
  {
    "id": 6,
    "name": "Salem Oasis",
    "location": "Tozeur",
    "region": "tozeur",
    "craft": "palm-weaver",
    "materials": ["palm-fronds", "date-fiber"],
    "culturalTags": ["desert-sustainable", "oasis-technique"],
    "quote": "Each basket holds the desert wind and palm shade - woven wisdom from our arid land.",
    "rating": 4.5,
    "totalOrders": 176,
    "yearsActive": 14,
    "specialty": "Date Harvest Baskets",
    "heritage": "Saharan palm craft",
    "accepts": "wholesale",
    "flag": "🇹🇳",
    "avatar": "/fake/artisans/artisan (22).png",
    "workshop": "/fake/workshops/workshop (2).png",
    "products": ["/fake/products/product (56).png", "/fake/products/product (75).png"]
  }
];
